[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mycalculatordapp = "4a2HFaLVkRpduW4bUfGgxPnbWTge88hYvHQkQA8arH1p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/vaishalichandrashekhar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000

[workspace]
members = [
    "programs/*"
]

[deploy]
timeout = 300

